# Generated by Django 5.0.6 on 2024-05-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=100)),
                ('longitud', models.FloatField(default=0)),
                ('latitud', models.FloatField(default=0)),
                ('estado_geo', models.BooleanField(default=False)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
