# Generated by Django 5.0.6 on 2024-05-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='latitud',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='longitud',
            field=models.FloatField(default=0, null=True),
        ),
    ]
